import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar"
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Abdelahi Reservation",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className="font-poppins min-h-screen flex flex-col gap-10 bg-[#e9e7e3]">
          <Navbar />
          <main>{children}</main>
          <Toaster />
          <Footer />
        </body>
      </SessionProvider>
    </html>
  );
}
